import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OuterSans } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={OuterSans.variable}>
      <body className={OuterSans.className}>{children}</body>
    </html>
  );
}
